CREATE TABLE TB_USUARIO (
  Id_Usuario INTEGER   NOT NULL ,
  Nome_Usuario VARCHAR(100)   NOT NULL ,
  Email_Usuario VARCHAR(45)   NOT NULL ,
  Senha_Usuario VARCHAR(25)   NOT NULL ,
  Tipo_Usuario VARCHAR(20)   NOT NULL ,
  Status_Usuario VARCHAR(1)   NOT NULL   ,
PRIMARY KEY(Id_Usuario));




CREATE TABLE TB_PROFESSOR (
  Id_Professor INTEGER   NOT NULL ,
  TB_USUARIO_Id_Usuario INTEGER   NOT NULL ,
  Nome_Professor VARCHAR(100)   NOT NULL ,
  Data_Nasc_Professor DATE   NOT NULL ,
  Fone_Professor VARCHAR(11)   NOT NULL ,
  Email_Professor VARCHAR(45)   NOT NULL ,
  Status_Professor VARCHAR(1)   NOT NULL   ,
PRIMARY KEY(Id_Professor)  ,
  FOREIGN KEY(TB_USUARIO_Id_Usuario)
    REFERENCES TB_USUARIO(Id_Usuario));


CREATE INDEX TB_PROFESSOR_FKIndex1 ON TB_PROFESSOR (TB_USUARIO_Id_Usuario);


CREATE INDEX IFK_Rel_13 ON TB_PROFESSOR (TB_USUARIO_Id_Usuario);


CREATE TABLE TB_DIRECAO (
  Id_Direcao INTEGER   NOT NULL ,
  TB_USUARIO_Id_Usuario INTEGER   NOT NULL ,
  Nome_Direcao VARCHAR(100)   NOT NULL ,
  Cargo_Direcao VARCHAR(20)   NOT NULL ,
  Fone_Direcao VARCHAR(11)   NOT NULL ,
  Email_Direcao VARCHAR(45)   NOT NULL ,
  Status_Direcao VARCHAR(1)   NOT NULL   ,
PRIMARY KEY(Id_Direcao)  ,
  FOREIGN KEY(TB_USUARIO_Id_Usuario)
    REFERENCES TB_USUARIO(Id_Usuario));


CREATE INDEX TB_DIRECAO_FKIndex1 ON TB_DIRECAO (TB_USUARIO_Id_Usuario);


CREATE INDEX IFK_Rel_12 ON TB_DIRECAO (TB_USUARIO_Id_Usuario);


CREATE TABLE TB_ALUNO (
  Id_Aluno INTEGER   NOT NULL ,
  TB_PROFESSOR_Id_Professor INTEGER   NOT NULL ,
  Nome_Aluno VARCHAR(100)   NOT NULL ,
  Data_Nasc_Aluno DATE   NOT NULL ,
  Sexo_Aluno CHAR(1)   NOT NULL ,
  Status_Aluno VARCHAR(1)   NOT NULL   ,
PRIMARY KEY(Id_Aluno)  ,
  FOREIGN KEY(TB_PROFESSOR_Id_Professor)
    REFERENCES TB_PROFESSOR(Id_Professor));


CREATE INDEX TB_ALUNO_FKIndex1 ON TB_ALUNO (TB_PROFESSOR_Id_Professor);


CREATE INDEX IFK_Rel_03 ON TB_ALUNO (TB_PROFESSOR_Id_Professor);


CREATE TABLE TB_TURMA (
  Id_Turma INTEGER   NOT NULL ,
  TB_ALUNO_Id_Aluno INTEGER   NOT NULL ,
  TB_PROFESSOR_Id_Professor INTEGER   NOT NULL ,
  Nome_Turma VARCHAR(50)   NOT NULL ,
  Periodo_Turma VARCHAR(20)    ,
  Sala_Turma VARCHAR(30)    ,
  Ano_Turma YEAR    ,
  Capacidade_Turma INTEGER      ,
PRIMARY KEY(Id_Turma, TB_ALUNO_Id_Aluno)    ,
  FOREIGN KEY(TB_PROFESSOR_Id_Professor)
    REFERENCES TB_PROFESSOR(Id_Professor),
  FOREIGN KEY(TB_ALUNO_Id_Aluno)
    REFERENCES TB_ALUNO(Id_Aluno));


CREATE INDEX TB_TURMA_FKIndex1 ON TB_TURMA (TB_PROFESSOR_Id_Professor);
CREATE INDEX TB_TURMA_FKIndex2 ON TB_TURMA (TB_ALUNO_Id_Aluno);


CREATE INDEX IFK_Rel_02 ON TB_TURMA (TB_PROFESSOR_Id_Professor);
CREATE INDEX IFK_Rel_07 ON TB_TURMA (TB_ALUNO_Id_Aluno);


CREATE TABLE TB_RESPONSAVEL (
  Id_Responsavel INTEGER   NOT NULL ,
  TB_USUARIO_Id_Usuario INTEGER   NOT NULL ,
  TB_ALUNO_Id_Aluno INTEGER   NOT NULL ,
  Nome_Responsavel VARCHAR(100)   NOT NULL ,
  Titular_Responsavel BOOL   NOT NULL ,
  Parentesco_Responsavel VARCHAR(10)   NOT NULL ,
  Email_Responsavel VARCHAR(45)   NOT NULL ,
  Fone_Responsavel VARCHAR(11)   NOT NULL ,
  Ender_Responsavel VARCHAR(100)   NOT NULL ,
  Status_Responsavel VARCHAR(1)   NOT NULL   ,
PRIMARY KEY(Id_Responsavel, TB_USUARIO_Id_Usuario)    ,
  FOREIGN KEY(TB_ALUNO_Id_Aluno)
    REFERENCES TB_ALUNO(Id_Aluno),
  FOREIGN KEY(TB_USUARIO_Id_Usuario)
    REFERENCES TB_USUARIO(Id_Usuario));


CREATE INDEX TB_RESPONSAVEL_FKIndex1 ON TB_RESPONSAVEL (TB_ALUNO_Id_Aluno);
CREATE INDEX TB_RESPONSAVEL_FKIndex2 ON TB_RESPONSAVEL (TB_USUARIO_Id_Usuario);


CREATE INDEX IFK_Rel_01 ON TB_RESPONSAVEL (TB_ALUNO_Id_Aluno);
CREATE INDEX IFK_Rel_11 ON TB_RESPONSAVEL (TB_USUARIO_Id_Usuario);


CREATE TABLE TB_PRESENCA (
  Id_Frequencia INTEGER   NOT NULL ,
  TB_PROFESSOR_Id_Professor INTEGER   NOT NULL ,
  TB_ALUNO_Id_Aluno INTEGER   NOT NULL ,
  Frequencia_Presenca DECIMAL   NOT NULL ,
  Data_Presenca DATE   NOT NULL ,
  Presenca BOOL   NOT NULL   ,
PRIMARY KEY(Id_Frequencia)    ,
  FOREIGN KEY(TB_ALUNO_Id_Aluno)
    REFERENCES TB_ALUNO(Id_Aluno),
  FOREIGN KEY(TB_PROFESSOR_Id_Professor)
    REFERENCES TB_PROFESSOR(Id_Professor));


CREATE INDEX TB_PRESENCA_FKIndex1 ON TB_PRESENCA (TB_ALUNO_Id_Aluno);
CREATE INDEX TB_PRESENCA_FKIndex2 ON TB_PRESENCA (TB_PROFESSOR_Id_Professor);


CREATE INDEX IFK_Rel_04 ON TB_PRESENCA (TB_ALUNO_Id_Aluno);
CREATE INDEX IFK_Rel_08 ON TB_PRESENCA (TB_PROFESSOR_Id_Professor);


CREATE TABLE TB_AGENDA (
  Id_Agenda INTEGER   NOT NULL ,
  TB_RESPONSAVEL_TB_USUARIO_Id_Usuario INTEGER   NOT NULL ,
  TB_DIRECAO_Id_Direcao INTEGER   NOT NULL ,
  TB_RESPONSAVEL_Id_Responsavel INTEGER   NOT NULL ,
  TB_PROFESSOR_Id_Professor INTEGER   NOT NULL ,
  TB_ALUNO_Id_Aluno INTEGER   NOT NULL ,
  Data_Agenda DATE   NOT NULL ,
  Recado_Agenda VARCHAR(255)   NOT NULL ,
  Tipo_Agenda VARCHAR(50)   NOT NULL ,
  Status_Agenda VARCHAR(30)   NOT NULL   ,
PRIMARY KEY(Id_Agenda)        ,
  FOREIGN KEY(TB_ALUNO_Id_Aluno)
    REFERENCES TB_ALUNO(Id_Aluno),
  FOREIGN KEY(TB_PROFESSOR_Id_Professor)
    REFERENCES TB_PROFESSOR(Id_Professor),
  FOREIGN KEY(TB_RESPONSAVEL_Id_Responsavel, TB_RESPONSAVEL_TB_USUARIO_Id_Usuario)
    REFERENCES TB_RESPONSAVEL(Id_Responsavel, TB_USUARIO_Id_Usuario),
  FOREIGN KEY(TB_DIRECAO_Id_Direcao)
    REFERENCES TB_DIRECAO(Id_Direcao));


CREATE INDEX TB_AGENDA_FKIndex1 ON TB_AGENDA (TB_ALUNO_Id_Aluno);
CREATE INDEX TB_AGENDA_FKIndex2 ON TB_AGENDA (TB_PROFESSOR_Id_Professor);
CREATE INDEX TB_AGENDA_FKIndex3 ON TB_AGENDA (TB_RESPONSAVEL_Id_Responsavel, TB_RESPONSAVEL_TB_USUARIO_Id_Usuario);
CREATE INDEX TB_AGENDA_FKIndex4 ON TB_AGENDA (TB_DIRECAO_Id_Direcao);


CREATE INDEX IFK_Rel_05 ON TB_AGENDA (TB_ALUNO_Id_Aluno);
CREATE INDEX IFK_Rel_06 ON TB_AGENDA (TB_PROFESSOR_Id_Professor);
CREATE INDEX IFK_Rel_09 ON TB_AGENDA (TB_RESPONSAVEL_Id_Responsavel, TB_RESPONSAVEL_TB_USUARIO_Id_Usuario);
CREATE INDEX IFK_Rel_10 ON TB_AGENDA (TB_DIRECAO_Id_Direcao);



