# Colocar aqui o nome da sua database
spring.datasource.url=jdbc:mysql://localhost:3306/EXAMPLE_CEI_NOME_DATABASE 

# Colocar o seu username do banco de dados
spring.datasource.username=username

# Colocar sua senha da database aqui
spring.datasource.password=12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mapeia os nomes das tabelas com
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
